### ISSUE TITLE
NullPointerException when trying to access waitForAngularRequestsToFinish()

### ISSUE THREAD

**Issue by jxmukherje** [paul-hammant/ngWebDriver#18]
java.lang.NullPointerException
	at businesscomponents.ngWebDriverTest.fnTestngWebBasic(ngWebDriverTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at supportlibraries.DriverScript.invokeBusinessComponent(DriverScript.java:443)
	at supportlibraries.DriverScript.executeTestcase(DriverScript.java:388)
	at supportlibraries.DriverScript.executeTestIterations(DriverScript.java:339)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at allocator.ParallelRunner.invokeTestScript(ParallelRunner.java:69)
	at allocator.ParallelRunner.run(ParallelRunner.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by manoj9788** [comment]
Do you still see this error ? Are using waitForAngularRequestsToFinish() on any Non-Angular pages ?
I have tried using it against our test app and it works good. 
I dont see any specs, config in your issue. Just a plain stack trace wont help.

**Comment by manoj9788** [comment]
Do you still see this error ? Are using waitForAngularRequestsToFinish() on any Non-Angular pages ?
I have tried using it against our test app and it works good. 
I dont see any specs, config in your issue. Just a plain stack trace wont help.

**Comment by manoj9788** [comment]
Do you still see this error ? Are using waitForAngularRequestsToFinish() on any Non-Angular pages ?
I have tried using it against our test app and it works good. 
I dont see any specs, config in your issue. Just a plain stack trace wont help.

**Comment by manoj9788** [comment]
Pls reopen if you see this error still.
