### ISSUE TITLE
ByAngular.model throws an Exception "org.openqa.selenium.WebDriverException: ha.element(...).injector(...) is undefined"

### ISSUE THREAD

**Issue by BalajiSingh** [paul-hammant/ngWebDriver#36]
Hi All,

As my site is developed using Angular Js and i need to get it automated so thought of using NgWebDriver as a choice and also to give an try once.
So i have written  a small piece of code  below to test  one particular functionality but then when i run it opens the browser even hooks on with url.

The real issue is while interacting with model webelement it throws error like "org.openqa.selenium.WebDriverException: ha.element(...).injector(...) is undefined".

Can somebody shed some light on this issue and provide an solution. And plz let me know where i am going wrong. 

Selenium version that iam using is : 2.53.1

public class Example1{

```
 public  FirefoxDriver driver;
 public  NgWebDriver ngWebDriver;
```

 @BeforeSuite
    public void before_suite() throws Exception {
         driver = new FirefoxDriver();
         driver.manage().timeouts().setScriptTimeout(30, TimeUnit.SECONDS);
        ngWebDriver = new NgWebDriver(driver);

```
}

  public void find_by_angular_model() throws Exception
   {

        driver.get("url");

        ngWebDriver.waitForAngularRequestsToFinish();

        Thread.sleep(2000);  //just used wait for time being.

        WebElement firstname = driver.findElement(ByAngular.buttonText("Create New SLI"));
         firstname.click();
        Thread.sleep(3000);        

       driver.findElement(ByAngular.model("SLI.prefFlightNumber1")).sendKeys("1111");
        Thread.sleep(2000);  
 }
```

}
# Console Output

FAILED: find_by_angular_model
org.openqa.selenium.WebDriverException: ha.element(...).injector(...) is undefined
Command duration or timeout: 20 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'PDCHP64-VM10085', ip: '10.27.23.235', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: f498255c-969a-482a-88eb-9b7188df6541
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
    at com.paulhammant.ngwebdriver.ByAngularModel.getObject(ByAngularModel.java:16)
    at com.paulhammant.ngwebdriver.ByAngular$BaseBy.findElement(ByAngular.java:170)
    at com.paulhammant.ngwebdriver.ByAngularModel.findElement(ByAngularModel.java:6)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
    at com.paulhammant.ngwebdriver.AngularAndWebDriverTest.find_by_angular_model(AngularAndWebDriverTest.java:92)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflec

**Comment by paul-hammant** [comment]
You need to help ngWebDriver find Angular in the page - https://github.com/paul-hammant/ngWebDriver#helping-ngwebdriver-find-angular-apps-in-a-page

**Comment by sunilpatro1985** [comment]
Angular 2 apps no longer supports model or bindings, instead use xpath / css.
