### ISSUE TITLE
Getting 	"at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127) Caused by: org.openqa.selenium.WebDriverException: unknown error: Cannot read property '$$testability' of undefined" while using ByAngular.model and sendKeys to that

### ISSUE THREAD

**Issue by GangadharanS** [paul-hammant/ngWebDriver#43]
Getting below error when i try to use ByAngular.model("dataModel.emailAddress").sendKeys("emailId"):

cucumber.runtime.CucumberException: org.openqa.selenium.WebDriverException: unknown error: Cannot read property '$$testability' of undefined
  (Session info: chrome=58.0.3029.81)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13 milliseconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'GASUBRA-IN-LE01', ip: '10.40.84.56', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\gasubra\AppData\Local\Temp\scoped_dir7228_9892}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.81, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 06d05ef9e9ed9232f26fe26244984f59

	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: org.openqa.selenium.WebDriverException: unknown error: Cannot read property '$$testability' of undefined
  (Session info: chrome=58.0.3029.81)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13 milliseconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'GASUBRA-IN-LE01', ip: '10.40.84.56', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\gasubra\AppData\Local\Temp\scoped_dir7228_9892}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.81, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 06d05ef9e9ed9232f26fe26244984f59
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:540)
	at com.paulhammant.ngwebdriver.ByAngularModel.getObject(ByAngularModel.java:16)
	at com.paulhammant.ngwebdriver.ByAngular$BaseBy.findElements(ByAngular.java:177)
	at com.paulhammant.ngwebdriver.ByAngularModel.findElements(ByAngularModel.java:6)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:359)
	at com.trimble.automation.framework.ui.internal.webobjects.FindActions$1.apply(FindActions.java:116)
	at com.trimble.automation.framework.ui.internal.webobjects.FindActions$1.apply(FindActions.java:105)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at com.trimble.automation.framework.ui.internal.webobjects.FindActions.findElements(FindActions.java:126)
	at com.trimble.automation.framework.ui.internal.webobjects.FindActions.findTextBox(FindActions.java:32)
	at com.trimble.automation.framework.ui.internal.webobjects.Page.findTextBox(Page.java:13)
	at com.trimble.connect.automation.script.webapp.pageobjects.home.projects.team.Team_Page_Objects.emailAddressTextBox(Team_Page_Objects.java:69)
	at com.trimble.connect.automation.script.webapp.pageobjects.home.projects.team.Team_Page.inviteUsers(Team_Page.java:89)
	at com.trimble.connect.automation.script.webapp.pageobjects.home.projects.team.Team_Page_Steps.inviteUsersToProject(Team_Page_Steps.java:35)
	at ✽.And User invites user "user.automation@mailinator.com" for "Admin" to the Project(java/com/trimble/connect/automation/script/webapp/tests/team/InviteUsers.feature:10)

Any help is highly appreciated.

**Comment by paul-hammant** [comment]
Can you help me reproduce this?  Specifically, a site in public that exhibits the same behavior, when ByAngular.model(..) is used.

**Comment by NehaDua** [comment]
I am also facing the same issue ..please help 

Starting ChromeDriver 2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9) on port 9812
Only local connections are allowed.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
May 18, 2017 12:35:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Cannot read property '$$testability' of undefined
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 129 milliseconds
Build info: version: 'unknown', revision: '86a5d70', time: '2017-02-16 07:47:51 -0800'
System info: host: 'AINLHSGH048RZJ7', ip: '10.230.10.248', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), userDataDir=C:\Users\AH0161~1\AppData\Local\Temp\2\scoped_dir16844_20383}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 0250ec0232745ba4e08e86ea53b2db54
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:537)
	at com.paulhammant.ngwebdriver.ByAngularModel.getObject(ByAngularModel.java:16)
	at com.paulhammant.ngwebdriver.ByAngular$BaseBy.findElement(ByAngular.java:166)
	at com.paulhammant.ngwebdriver.ByAngularModel.findElement(ByAngularModel.java:6)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
	at TestSelenium.main(TestSelenium.java:85)
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\HP\Unified Functional Testing\bin\java_shared\classes";"C:\Program Files (x86)\HP\Unified Functional Testing\bin\java_shared\classes\jasmine.jar"

**Comment by NehaDua** [comment]
My Code:





import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;

import COM.ibm.db2.jdbc.app.*;

import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.junit.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.HasCapabilities;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeDriverService;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.interactions.touch.FlickAction;
import org.openqa.selenium.internal.Locatable;
import org.openqa.selenium.internal.WrapsDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.aonhewitt.aft.utility.SharedResource;
import com.aonhewitt.aft.utility.UtilityClass;
import com.paulhammant.ngwebdriver.ByAngular;
import com.paulhammant.ngwebdriver.NgWebDriver;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
public class TestSelenium 
{
                

    private static NgWebDriver ngDriver;
    private WebDriverWait wait;
 
 
    private int wait_seconds = 3;
    private int highlight_timeout = 100;
    private Actions actions;

                public static WebElement element;
                public static NgWebDriver ngWebDriver;

                public static void main(String[] args) throws ParseException, ClassNotFoundException, SQLException 
                {
                	ChromeDriver  driver = new ChromeDriver();
                    driver.manage().timeouts().setScriptTimeout(30, TimeUnit.SECONDS);
                    ngWebDriver = new NgWebDriver(driver);

                    driver.get("https://angularjs.org/");
                    ngWebDriver.waitForAngularRequestsToFinish();

                    WebElement firstname = driver.findElement(ByAngular.model("yourName"));
                   
                   firstname.sendKeys("NehaDua");
                   Assert.assertEquals(driver.findElement(By.xpath("//input")).getAttribute("value"), "NehaDua");
                }
                
}

**Comment by GangadharanS** [comment]
Hi Paul,
Is there any solution identified for this..

FYI, The same issue has been identified in protractor
https://github.com/angular/protractor/issues/4233.

Thanks
Gangadhar

**Comment by paul-hammant** [comment]
I've got @NehaDua's code working:

```
        ChromeDriver  driver = new ChromeDriver();
        driver.manage().timeouts().setScriptTimeout(30, TimeUnit.SECONDS);
        ngWebDriver = new NgWebDriver(driver).withRootSelector("[app-run=\"hello.html\"]");
        ByAngular.Factory byAngular = ngWebDriver.makeByAngularFactory();

        driver.get("https://angularjs.org/");
        ngWebDriver.waitForAngularRequestsToFinish();

        WebElement firstname = driver.findElement(byAngular.model("yourName"));

        firstname.sendKeys("NehaDua");
        assertEquals(driver.findElement(By.xpath("//input")).getAttribute("value"), "NehaDua");
``` 

The AngularJS home page does some very custom bootstrapping of multiple AngularJS examples, and therefore needs a custom root selector.

Selector examples here - https://www.w3schools.com/cssref/css_selectors.asp

Folks: Any other examples of "$$testability undefined" in public folks, that cannot be solved with a root selector ????

**Comment by GangadharanS** [comment]
Thanks Paul. This works perfect.

**Comment by paul-hammant** [comment]
You're welcome, closing the issue now.
