### ISSUE TITLE
my script is time out  while running using ng webdriver

### ISSUE THREAD

**Issue by nileshraval** [paul-hammant/ngWebDriver#88]
I am using ng webdriver  for my angular web application here is my script. 
static WebDriver driver;
 static NgWebDriver ngdriver;
 
 public static void main(String[] args) throws InterruptedException{
 System.setProperty("webdriver.chrome.driver","E:\\AutomationFlourish\\chromedriver\\chromedriver.exe");
  driver = new ChromeDriver();

  //Sample AngularJs Webpage
  driver.get("https://uat.flourishsoftware.com/login");
  driver.manage().window().maximize();

  //Creating an instance of NgWebDriver
  ngdriver = new NgWebDriver((JavascriptExecutor) driver);
  ngdriver.waitForAngularRequestsToFinish();
  driver.findElement(ByAngular.model("$ctrl.requester.username")).sendKeys("Test Company");

**error**
Exception in thread "main" org.openqa.selenium.ScriptTimeoutException: script timeout
  (Session info: chrome=78.0.3904.70)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-DH1DMSN', ip: '192.168.0.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 78.0.3904.70, chrome: {chromedriverVersion: 78.0.3904.70 (edb9c9f3de024..., userDataDir: C:\Users\DELL\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:49396}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 3ff87265306fd14552cb7ec620e9b978
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:506)
	at com.paulhammant.ngwebdriver.NgWebDriver.waitForAngularRequestsToFinish(NgWebDriver.java:68)
	at dropdown.AngularWebDriver2.main(AngularWebDriver2.java:24)

**Comment by paul-hammant** [comment]
I've played with yours for some time and I can't get it to work. You need to use .withRootSelector(..) to find the angular root. I don't know how your app is booting angular. Can you ask your developers?

**Comment by akbhartiya** [comment]
Hi @nileshraval,  are you able to resolve this issue? I am also facing same Timeout exception issue in NgWebDriver implementation.
