### ISSUE TITLE
Getting script timeout error when i use ngwebdriver

### ISSUE THREAD

**Issue by vikasranjan89** [paul-hammant/ngWebDriver#93]
org.openqa.selenium.ScriptTimeoutException: script timeout
  (Session info: chrome=78.0.3904.87)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'INN1SLPMQ2', ip: '10.141.23.159', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_74'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 78.0.3904.87, chrome: {chromedriverVersion: 78.0.3904.70 (edb9c9f3de024..., userDataDir: C:\Users\1598477\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:51451}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: e6b7633ea3f10532952491a1877827b0
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:506)
	at com.paulhammant.ngwebdriver.NgWebDriver.waitForAngularRequestsToFinish(NgWebDriver.java:68)
	at com.standardchartered.cos.module.customeroriginationsystems.CustomerOriginSystemsGlue.waitForFewSeconds(CustomerOriginSystemsGlue.java:69)
	at ✽.wait for angular to be sync(features/cos_hkid_cc_ntb_Decline.feature:10

**Comment by paul-hammant** [comment]
If you don't use waitForAngularRequestsToFinish() an instead Thread.sleep(10000) what happens?

**Comment by vikasranjan89** [comment]
It works fine. Yesterday I downloaded 1.1.5 version and used root selector,  it doesn't throw any error.
But I am curious to know about rootselector. Kindly help me with the information

**Comment by paul-hammant** [comment]
Read here - https://github.com/paul-hammant/ngWebDriver#waiting-for-angular-to-finish-async-activity

And here - https://github.com/paul-hammant/ngWebDriver#helping-ngwebdriver-find-angular-apps-in-a-page
